// <auto-generated />
using System;
using Pulse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Pulse.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PulseDbContext))]
    [Migration("20260906215101_AddLoanedFromEngineerIdToTasks")]
    partial class AddLoanedFromEngineerIdToTasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pulse.Domain.CheckIns.CheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Blockers")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("blockers");

                    b.Property<string>("Completed")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("work_completed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("EngineerId")
                        .HasColumnType("uuid")
                        .HasColumnName("engineer_id");

                    b.Property<string>("PlannedNext")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("planned");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("EngineerId", "Date", "ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_check_ins_engineer_id_date_project_id");

                    b.ToTable("check_ins", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Email.FailedEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_body");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<DateTime>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)")
                        .HasColumnName("subject");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("to");

                    b.HasKey("Id");

                    b.HasIndex("IsResolved", "CreatedAt")
                        .HasDatabaseName("ix_failed_emails_is_resolved_created_at");

                    b.ToTable("failed_emails", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Engineers.Engineer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BaselineCycleDays")
                        .HasColumnType("integer")
                        .HasColumnName("baseline_cycle_days");

                    b.Property<int>("BaselinePoints")
                        .HasColumnType("integer")
                        .HasColumnName("baseline_points");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Discipline")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("discipline");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsQa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_qa");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_expires_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<string>("Team")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_engineers_email");

                    b.ToTable("engineers", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Engineers.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EngineerID")
                        .HasColumnType("uuid")
                        .HasColumnName("engineer_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("EngineerID", "IsRevoked")
                        .HasDatabaseName("ix_refresh_tokens_engineer_id_is_revoked");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Epics.Epic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcceptanceCriteria")
                        .HasColumnType("text")
                        .HasColumnName("acceptance_criteria");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_epics_project_id");

                    b.HasIndex("SprintId")
                        .HasDatabaseName("ix_epics_sprint_id");

                    b.ToTable("epics", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Escalations.EscalationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("FiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fired_at");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "Level")
                        .HasDatabaseName("ix_escalation_events_task_id_level");

                    b.ToTable("escalation_events", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Feedback.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EngineerId")
                        .HasColumnType("uuid")
                        .HasColumnName("engineer_id");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateOnly>("WeekOf")
                        .HasColumnType("date")
                        .HasColumnName("week_of");

                    b.HasKey("Id");

                    b.HasIndex("WeekOf")
                        .HasDatabaseName("ix_feedback_week_of");

                    b.ToTable("feedback", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kind");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_user_id_sent_at");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Overrides.OverworkOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EngineerId")
                        .HasColumnType("uuid")
                        .HasColumnName("engineer_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("GrantedById")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("EngineerId", "ExpiresAt")
                        .HasDatabaseName("ix_overwork_overrides_engineer_id_expires_at");

                    b.ToTable("overwork_overrides", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_team_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_projects_status");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Projects.ProjectFollow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid")
                        .HasColumnName("follower_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_follows_project_id");

                    b.HasIndex("FollowerId", "ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_project_follows_follower_project");

                    b.ToTable("project_follows", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Projects.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("EngineerId")
                        .HasColumnType("uuid")
                        .HasColumnName("engineer_id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("ProjectId", "EngineerId");

                    b.HasIndex("EngineerId")
                        .HasDatabaseName("ix_project_members_engineer_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_members_project_id");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Projects.WikiPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_wiki_pages_project_id");

                    b.ToTable("wiki_pages", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Projects.WikiPageRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<Guid>("WikiPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("wiki_page_id");

                    b.HasKey("Id");

                    b.HasIndex("WikiPageId")
                        .HasDatabaseName("ix_wiki_page_revisions_wiki_page_id");

                    b.ToTable("wiki_page_revisions", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Vitals.VitalsResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EngineerId")
                        .HasColumnType("uuid")
                        .HasColumnName("engineer_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateOnly>("WeekOf")
                        .HasColumnType("date")
                        .HasColumnName("week_of");

                    b.HasKey("Id");

                    b.HasIndex("EngineerId", "WeekOf")
                        .IsUnique()
                        .HasDatabaseName("ix_vitals_responses_engineer_week");

                    b.ToTable("vitals_responses", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Reports.WeeklyReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExecutiveSummary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("executive_summary");

                    b.Property<string>("KeyAccomplishments")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("key_accomplishments");

                    b.Property<string>("PlannedNextWeek")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("planned_next_week");

                    b.Property<string>("ResourcingNotes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("resourcing_notes");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("SubmittedById")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly>("WeekOf")
                        .HasColumnType("date")
                        .HasColumnName("week_of");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "WeekOf")
                        .IsUnique()
                        .HasDatabaseName("ix_weekly_reports_team_id_week_of");

                    b.ToTable("weekly_reports", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Sprints.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CapacityPoints")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_points");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Goal")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("goal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateOnly?>("ShowAndTellDate")
                        .HasColumnType("date")
                        .HasColumnName("show_and_tell_date");

                    b.Property<string>("ShowAndTellNotes")
                        .HasColumnType("text")
                        .HasColumnName("show_and_tell_notes");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_sprints_project_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_sprints_team_id");

                    b.ToTable("sprints", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Sprints.SprintRetrospective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionItems")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("action_items");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("NeedsImprovement")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("needs_improvement");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WentWell")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("went_well");

                    b.HasKey("Id");

                    b.HasIndex("SprintId")
                        .IsUnique()
                        .HasDatabaseName("ix_sprint_retrospectives_sprint_id");

                    b.ToTable("sprint_retrospectives", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Tasks.PulseTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcceptanceCriteria")
                        .HasColumnType("text")
                        .HasColumnName("acceptance_criteria");

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<DateOnly?>("ActualEndDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_end_date");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<string>("BlockerReason")
                        .HasColumnType("text")
                        .HasColumnName("blocker_reason");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Discipline")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("discipline");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("EpicId")
                        .HasColumnType("uuid")
                        .HasColumnName("epic_id");

                    b.Property<Guid?>("LoanedFromEngineerId")
                        .HasColumnType("uuid")
                        .HasColumnName("loaned_from_engineer_id");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_task_id");

                    b.Property<string>("PauseNote")
                        .HasColumnType("text")
                        .HasColumnName("pause_note");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<bool>("PausedByProject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("paused_by_project");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("QaTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("qa_task_id");

                    b.Property<Guid?>("ReactivatedByEngineerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reactivated_by_engineer_id");

                    b.Property<string>("ReactivationReason")
                        .HasColumnType("text")
                        .HasColumnName("reactivation_reason");

                    b.Property<bool>("RequiresQa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_qa");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StatusBeforePause")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_before_pause");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_tasks_due_date");

                    b.HasIndex("AssigneeId", "Status")
                        .HasDatabaseName("ix_tasks_assignee_id_status");

                    b.HasIndex("ProjectId", "Status")
                        .HasDatabaseName("ix_tasks_project_id_status");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Tasks.Subtask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean")
                        .HasColumnName("is_done");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_subtasks_task_id");

                    b.ToTable("subtasks", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Tasks.TaskComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_task_comments_task_id");

                    b.ToTable("task_comments", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Tasks.TaskDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BlockingTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocking_task_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DependentTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("dependent_task_id");

                    b.HasKey("Id");

                    b.HasIndex("BlockingTaskId")
                        .HasDatabaseName("ix_task_dependencies_blocking_task_id");

                    b.HasIndex("DependentTaskId")
                        .HasDatabaseName("ix_task_dependencies_dependent_task_id");

                    b.HasIndex("BlockingTaskId", "DependentTaskId")
                        .IsUnique()
                        .HasDatabaseName("ix_task_dependencies_unique_pair");

                    b.ToTable("task_dependencies", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Tasks.TaskEstimationSession", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRevealed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revealed");

                    b.HasKey("TaskId");

                    b.ToTable("task_estimation_sessions", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Tasks.TaskEstimationVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uuid")
                        .HasColumnName("voter_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_task_estimation_votes_task_id");

                    b.HasIndex("TaskId", "VoterId")
                        .IsUnique()
                        .HasDatabaseName("ix_task_estimation_votes_task_voter");

                    b.ToTable("task_estimation_votes", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Tasks.TaskHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("field");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("to_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("from_value");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_task_history_task_id");

                    b.ToTable("task_history", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("TeamLeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_lead_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_name");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.TimeEntries.ActiveTimer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EngineerId")
                        .HasColumnType("uuid")
                        .HasColumnName("engineer_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("EngineerId")
                        .IsUnique()
                        .HasDatabaseName("ix_active_timers_engineer_id");

                    b.ToTable("active_timers", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.TimeEntries.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("EngineerId")
                        .HasColumnType("uuid")
                        .HasColumnName("engineer_id");

                    b.Property<decimal>("Hours")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("hours");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_time_entries_task_id");

                    b.HasIndex("EngineerId", "Date")
                        .HasDatabaseName("ix_time_entries_engineer_id_date");

                    b.ToTable("time_entries", (string)null);
                });

            modelBuilder.Entity("Pulse.Infrastructure.Persistence.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts");

                    b.HasKey("Id");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_audit_log_actor_id");

                    b.HasIndex("Ts")
                        .HasDatabaseName("ix_audit_log_ts");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Pulse.Infrastructure.Persistence.ThresholdSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("threshold_settings", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Projects.WikiPageRevision", b =>
                {
                    b.HasOne("Pulse.Domain.Projects.WikiPage", null)
                        .WithMany()
                        .HasForeignKey("WikiPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pulse.Domain.Tasks.TaskHistory", b =>
                {
                    b.HasOne("Pulse.Domain.Tasks.PulseTask", null)
                        .WithMany("History")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pulse.Domain.Tasks.PulseTask", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
