using Pulse.Application.Reports;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Pulse.Api.Reports;

/// <summary>
/// Renders a LeadershipReportDto to a PDF byte array using QuestPDF.
/// Lives in the API project because PDF rendering is a presentation concern.
/// </summary>
public static class LeadershipReportPdfRenderer
{
    static LeadershipReportPdfRenderer()
    {
        // Community license is free for open-source and internal tooling.
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public static byte[] Render(LeadershipReportDto report)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(30);
                page.DefaultTextStyle(t => t.FontSize(9).FontFamily("Arial"));

                page.Header().Element(ComposeHeader(report));
                page.Content().Element(ComposeContent(report));
                page.Footer().AlignCenter().Text(t =>
                {
                    t.Span("Generated by Pulse · ").FontColor(Colors.Grey.Medium);
                    t.Span(DateTime.UtcNow.ToString("dd MMM yyyy HH:mm") + " UTC").FontColor(Colors.Grey.Medium);
                });
            });
        }).GeneratePdf();
    }

    private static Action<IContainer> ComposeHeader(LeadershipReportDto report) =>
        c => c.PaddingBottom(12).Column(col =>
        {
            col.Item().Text("Leadership Report").FontSize(18).Bold();
            col.Item().Text($"Week of {report.WeekOf}").FontSize(10).FontColor(Colors.Grey.Darken2);
        });

    private static Action<IContainer> ComposeContent(LeadershipReportDto report) =>
        c => c.Column(col =>
        {
            // Summary row
            col.Item().PaddingBottom(16).Row(row =>
            {
                SummaryCell(row, "Delivered this week", report.TotalDeliveredPoints.ToString(), Colors.Green.Darken2);
                SummaryCell(row, "Previous week", report.PreviousWeekPoints.ToString(), Colors.Grey.Darken2);

                if (report.TotalDeliveredPoints > 0 && report.PreviousWeekPoints > 0)
                {
                    var delta = report.TotalDeliveredPoints - report.PreviousWeekPoints;
                    var pct   = (int)Math.Round((double)delta / report.PreviousWeekPoints * 100);
                    var sign  = delta >= 0 ? "+" : "";
                    var color = delta >= 0 ? Colors.Green.Darken2 : Colors.Red.Darken2;
                    SummaryCell(row, "vs last week", $"{sign}{pct}%", color);
                }
            });

            // Team capacity table
            col.Item().PaddingBottom(4).Text("Team Capacity").FontSize(11).Bold();
            col.Item().PaddingBottom(16).Element(EngineersTable(report.Engineers));

            // At-risk tasks
            if (report.Escalations.Count > 0)
            {
                col.Item().PaddingBottom(4).Text("At-Risk Tasks").FontSize(11).Bold();
                col.Item().PaddingBottom(16).Element(EscalationsTable(report.Escalations));
            }

            // Active blockers
            if (report.Blockers.Count > 0)
            {
                col.Item().PaddingBottom(4).Text("Active Blockers").FontSize(11).Bold();
                col.Item().Element(BlockersTable(report.Blockers));
            }
        });

    private static void SummaryCell(RowDescriptor row, string label, string value, string color)
    {
        row.RelativeItem().Border(1).BorderColor(Colors.Grey.Lighten2)
            .Padding(8).Column(c =>
            {
                c.Item().Text(value).FontSize(18).Bold().FontColor(color);
                c.Item().Text(label).FontSize(8).FontColor(Colors.Grey.Darken1);
            });
    }

    private static Action<IContainer> EngineersTable(IReadOnlyList<EngineerUtilizationEntry> engineers) =>
        c => c.Table(table =>
        {
            table.ColumnsDefinition(cols =>
            {
                cols.RelativeColumn(3); // name
                cols.RelativeColumn();  // tasks
                cols.RelativeColumn();  // points
                cols.RelativeColumn();  // baseline
                cols.RelativeColumn();  // check-ins
                cols.RelativeColumn();  // blockers
                cols.RelativeColumn();  // flag
            });

            HeaderCell(table, "Engineer");
            HeaderCell(table, "Tasks");
            HeaderCell(table, "Points");
            HeaderCell(table, "Baseline");
            HeaderCell(table, "Check-ins");
            HeaderCell(table, "Blockers");
            HeaderCell(table, "Flag");

            foreach (var eng in engineers)
            {
                DataCell(table, eng.Name, bold: true);
                DataCell(table, eng.ActiveTasks.ToString());
                DataCell(table, eng.TotalPoints.ToString());
                DataCell(table, eng.BaselinePoints.ToString(), color: Colors.Grey.Darken1);
                DataCell(table, $"{eng.CheckInsThisWeek}/5");
                DataCell(table, eng.Blockers.ToString());
                table.Cell().Padding(4).Text(eng.IsOverworked ? "⚠ overworked" : "")
                    .FontColor(eng.IsOverworked ? Colors.Red.Darken2 : Colors.White);
            }
        });

    private static Action<IContainer> EscalationsTable(IReadOnlyList<EscalationReportEntry> escalations) =>
        c => c.Table(table =>
        {
            table.ColumnsDefinition(cols =>
            {
                cols.RelativeColumn(4);
                cols.RelativeColumn(2);
                cols.RelativeColumn();
            });

            HeaderCell(table, "Task");
            HeaderCell(table, "Due");
            HeaderCell(table, "Level");

            foreach (var esc in escalations)
            {
                DataCell(table, esc.Title);
                DataCell(table, esc.DueDate?.ToString("dd MMM yyyy") ?? "—");
                var levelLabel = esc.Level switch
                {
                    "Overdue"  => "Overdue",
                    "TMinus1"  => "T-1",
                    _          => "T-3",
                };
                var levelColor = esc.Level == "Overdue" || esc.Level == "TMinus1"
                    ? Colors.Red.Darken2
                    : Colors.Orange.Darken2;
                table.Cell().Padding(4).Text(levelLabel).Bold().FontColor(levelColor);
            }
        });

    private static Action<IContainer> BlockersTable(IReadOnlyList<BlockerReportEntry> blockers) =>
        c => c.Column(col =>
        {
            foreach (var b in blockers)
            {
                col.Item().PaddingBottom(4)
                    .Border(1).BorderColor(Colors.Red.Lighten3)
                    .Background(Colors.Red.Lighten5)
                    .Padding(6).Column(inner =>
                    {
                        inner.Item().Text(b.Title).Bold().FontColor(Colors.Red.Darken3);
                        inner.Item().Text(b.Reason).FontColor(Colors.Red.Darken2);
                    });
            }
        });

    private static void HeaderCell(TableDescriptor table, string text) =>
        table.Cell()
            .Background(Colors.Grey.Lighten3)
            .Padding(4)
            .Text(text)
            .Bold()
            .FontSize(8);

    private static void DataCell(TableDescriptor table, string text, bool bold = false, string? color = null)
    {
        var t = table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text(text);
        if (bold)  t.Bold();
        if (color is not null) t.FontColor(color);
    }
}
